name: Release

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Package
        run: sh package.sh

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: vrm_rigify.zip